# Generated by Django 2.1.7 on 2019-03-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sponser_info',
            new_name='Sponsor_info',
        ),
    ]
