# Generated by Django 2.1.7 on 2019-03-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_auto_20190316_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor_info',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
