# Generated by Django 2.1.7 on 2019-03-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_auto_20190316_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor_info',
            name='contact_no',
            field=models.IntegerField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
